spring.datasource:
  url: "jdbc:mariadb://localhost:3306/warehouse_manager"
  username: "bob"
  password: "bobhasapassword"
  # Change the driver name to whatever Connector uses
  driver-class-name: "org.mariadb.jdbc.Driver"


spring.jpa.hibernate.ddl-auto: "none"

authentication:
  secret: "youcansettheseasenvironmentvariablesyouknow"
  # See https://docs.oracle.com/javase/8/docs/api/java/time/Duration.html#parse-java.lang.CharSequence-
  # for info on the duration format
  duration: "10m"
  default-user:
    # Credentials for the default user
    username: ""
    password: ""
    email: ""
    roles:
      - "ROLE_SYSTEM_ADMIN"

