spring.datasource:
  url: "jdbc:mariadb://localhost:3306/warehouse_manager"
  username: ""
  password: ""
  driver-class-name: "org.mariadb.jdbc.Driver"

spring.jpa.hibernate.ddl-auto: "create"

authentication:
  duration: "10m"
  default-user:
    username: "endri"
    password: "hello there"
    email: "endri-kurushi@hotmail.com"
    roles:
      - "ROLE_SYSTEM_ADMIN"